#!/bin/sh
#
# Gradle start-up script for POSIX generated by "Gradle Init".
#
# Important for running:
#
# (1) You need a POSIX-compliant shell to run this script. If your /bin/sh is
#     noncompliant, but you have some other POSIX-compliant shell such as ksh or
#     bash, then to run this script, type that shell name before the name of
#     this script. For example:
#
#         ksh Gradle
#
# Executing it directly as ./gradlew should work, too.

# Attempt to set APP_HOME
# Resolve links: $0 may be a link
app_path=$0
# shellcheck disable=SC2034
APP_HOME=$( cd "${app_path%"${app_path##*/}"}" > /dev/null && pwd -P ) || exit

# Use the maximum available, or set MAX_FD != -1 to use that value.
MAX_FD=maximum

warn () {
    echo "$*"
} >&2

die () {
    echo
    echo "$*"
    echo
    exit 1
} >&2

# Determine the Java command to use to start the JVM.
if [ -n "$JAVA_HOME" ] ; then
    if [ -x "$JAVA_HOME/jre/sh/java" ] ; then
        JAVACMD=$JAVA_HOME/jre/sh/java
    else
        JAVACMD=$JAVA_HOME/bin/java
    fi
    if [ ! -x "$JAVACMD" ] ; then
        die "ERROR: JAVA_HOME is set to an invalid directory: $JAVA_HOME"
    fi
else
    JAVACMD=java
    if ! command -v java > /dev/null 2>&1; then
        die "ERROR: JAVA_HOME is not set and no 'java' command could be found in your PATH."
    fi
fi

# Use the Gradle wrapper
exec "$JAVACMD" \
  -classpath "$APP_HOME/gradle/wrapper/gradle-wrapper.jar" \
  org.gradle.wrapper.GradleWrapperMain "$@"
